language: python
python:
  - "2.7"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - uuid-dev
    - gcc-4.8
    - g++-4.8
install:
  - CXX=g++-4.8 ./.xapian_travis.sh 1.2.21
  - pip install -r requirements.txt
  - pip install coveralls webtest
script:
  - python manage.py migrate
  - python manage.py test
  - coverage run --source="." manage.py test
after_success: coveralls
